/var/log/tor/notices.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 0640 tor tor
    sharedscripts
    postrotate
        /usr/bin/pkill -HUP tor 2>/dev/null || true
    endscript
}
